var Block = require('../models/Block');
var MockUserData = require('./MockUserData');

var questions = {
    "language": "it",
    "items":[
    {
        "id": 1,
        "title": 'Chi é #1',
        "description": 'Nome di tuo padre',
        "tooltip": 'Nome di tuo padre',
        "x" : 3,
        "y" : 2,
    },
    {
        "id": 2,
        "title": 'Chi é #2',
        "description": 'Nome di tua madre',
        "tooltip": 'Nome di tua madre',
        "x" : 3,
        "y" : 4,
    },
    {
        "id": 3,
        "title": 'Cos\é #3',
        "description": 'Quello che ho ammirato in #1',
        "tooltip": 'Quello che ho ammirato in #1',
        "x" : 2,
        "y" : 2,
    },
    {
        "id": 4,
        "title": 'Cos\'é #4',
        "description": 'Quello che ho ammirato in #2',
        "tooltip": 'Quello che ho ammirato in #2',
        "x" : 4,
        "y" : 4,
    },
    {
        "id": 5,
        "title": 'Chi é #5',
        "description": 'Nome nonno paterno',
        "tooltip": 'Nome del nonno paterno',
        "x" : 3,
        "y" : 1,
    },
    {
        "id": 6,
        "title": 'Chi é #6',
        "description": 'Nome nonna materna',
        "tooltip": 'Nome della nonna materna',
        "x" : 3,
        "y" : 5,
    },
    {
        "id": 7,
        "title": 'Cos\'é #7',
        "description": 'Fede o persuasione religiosa papá',
        "tooltip": 'Fede religiosa papá',
        "x" : 4,
        "y" : 2,
    },
    {
        "id": 8,
        "title": 'Cos\'é #8',
        "description": 'Fede o persuasione religiosa mamma',
        "tooltip": 'Fede religiosa mamma',
        "x" : 2,
        "y" : 4,
    },
    {
        "id": 9,
        "title": 'Cos\'é #9',
        "description": 'Caratteristica del nonno maggiormente impressa in papá',
        "tooltip": 'Caratteristica nonno impressa in papá',
        "x" : 2,
        "y" : 1,
    },
    {
        "id": 10,
        "title": 'Cos\'é #10',
        "description": 'Tratto passato della nonna, tratto amaro, passato da nonna a mamma',
        "tooltip": 'Il modo di vostra nonna che ha intimidito o spaventato la mamma',
        "x" : 4,
        "y" : 5,
    },
    {
        "id": 11,
        "x" : 4,
        "y" : 1,
        "title": 'Cos\' é #11',
        "description": 'La religione del nonno paterno',
        "tooltip": 'Religione nonno paterno',
    },
    {
        "id": 12,
        "x" : 2,
        "y" : 5,
        "title": 'Cos\' é #12',
        "description": 'La piú grande paura della nonna materna',
        "tooltip": 'Piú grande paura nonna materna',
    },
    {
        "id": 13,
        "x" : 3,
        "y" : 0,
        "title": 'Chi é #13',
        "description": 'La madre del nonno paterno',
        "tooltip": 'Madre nonno paterno',
    },
    {
        "id": 14,
        "x" : 3,
        "y" : 6,
        "title": 'Chi é #14',
        "description": 'Il padre della nonna materna',
        "tooltip": 'Padre nonna materna',
    },
    {
        "id": 15,
        "x" : 2,
        "y" : 6,
        "title": 'Cos\' é #15',
        "description": 'Religione del #14 (padre della nonna materna)',
        "tooltip": 'Religione del #14',
    },
    {
        "id": 16,
        "x" : 4,
        "y" : 0,
        "title": 'Cos\' é #16',
        "description": 'Professione del #13 (madre del nonno paterno)',
        "tooltip": 'Professione del #13',
    },
    {
        "id": 17,
        "x" : 4,
        "y" : 6,
        "title": 'Cos\' é #17',
        "description": 'Professione del #14 (padre della nonna materna)',
        "tooltip": 'Professione del #14',
    },
    {
        "id": 18,
        "x" : 2,
        "y" : 0,
        "title": 'Chi é #18',
        "description": 'Nome sposo del #13 (madre del nonno paterno)',
        "tooltip": 'Nome sposo del #13',
    },
    {
        "id": 19,
        "x" : 2,
        "y" : 3,
        "title": 'Chi é #19',
        "description": 'La persona che piú amate',
        "tooltip": 'Chi piú amate',
    },
    {
        "id": 20,
        "x" : 1,
        "y" : 2,
        "title": 'Chi é #20',
        "description": 'Madre del #19',
        "tooltip": 'Madre del #19',
    },
    {
        "id": 21,
        "x" : 1,
        "y" : 3,
        "title": 'Cos\' é #21',
        "description": 'Cosa hanno in cumune #19 e #20',
        "tooltip": 'Cosa in cumune #19 e #20',
    },
    {
        "id": 22,
        "x" : 0,
        "y" : 3,
        "title": 'Chi é #22',
        "description": 'Cosa vi piace di meno del #20',
        "tooltip": 'Cosa disprezzate del #20',
    },
    {
        "id": 23,
        "x" : 0,
        "y" : 2,
        "title": 'Chi é #23',
        "description": 'Cosa ammirate di piú del #20',
        "tooltip": 'Cosa piú vi piace del #20',
    },
    {
        "id": 24,
        "x" : 4,
        "y" : 3,
        "title": 'Chi é #24',
        "description": 'Persona che odiamo di piú',
        "tooltip": 'Persona piú odiata',
    },
    {
        "id": 25,
        "x" : 5,
        "y" : 3,
        "title": 'Cos\' é #25',
        "description": 'Perché odiamo il #24',
        "tooltip": 'Perché odiamo il #24',
    },
    {
        "id": 26,
        "x" : 5,
        "y" : 2,
        "title": 'Chi é #26',
        "description": 'Il padre del #24',
        "tooltip": 'Padre del #24',
    },
    {
        "id": 27,
        "x" : 6,
        "y" : 2,
        "title": 'Chi é #27',
        "description": 'Il tratto piú brutto del padre del #24 (#26 - persona che odiamo di piú)',
        "tooltip": 'Il tratto piú brutto del #26',
    },
    {
        "id": 28,
        "x" : 6,
        "y" : 3,
        "title": 'Cos\' é #28',
        "description": 'Che valore ha il #24',
        "tooltip": 'Che valore ha il #24',
    },
    {
        "id": 29,
        "x" : 5,
        "y" : 4,
        "title": 'Cos\' é #29',
        "description": 'Cosa che non ci piace di noi stessi',
        "tooltip": 'Cosa non vi piace di voi',
    },
    {
        "id": 30,
        "x" : 1,
        "y" : 4,
        "title": 'Cos\' é #30',
        "description": 'Cosa che ci piace di piú di noi stessi',
        "tooltip": 'Cosa vi piace di voi',
    },
    {
        "id": 31,
        "x" : 0,
        "y" : 4,
        "title": 'Cos\' é #31',
        "description": 'Che valore ha il #30',
        "tooltip": 'Il valore del #30',
    },
    {
        "id": 32,
        "x" : 6,
        "y" : 4,
        "title": 'Cos\' é #32',
        "description": 'Cha valore ho io',
        "tooltip": 'Quanto vali?',
    },
    {
        "id": 33,
        "x" : 5,
        "y" : 1,
        "title": 'Cos\' é #33',
        "description": 'Cosa piú volete del mondo materiale',
        "tooltip": 'Cosa desideri materialmente',
    },
    {
        "id": 34,
        "x" : 6,
        "y" : 1,
        "title": 'Chi é #34',
        "description": 'Chi ha quello che voi volete',
        "tooltip": 'Chi ha quello che voi volete',
    },
    {
        "id": 35,
        "x" : 1,
        "y" : 1,
        "title": 'Cos\' é #35',
        "description": 'Cosa avete ereditato dal #9 (Caratteristica del nonno maggiormente impressa in papá)',
        "tooltip": 'Che ereditá avete dal #9',
    },
    {
        "id": 36,
        "x" : 0,
        "y" : 1,
        "title": 'Cos\' é #36',
        "description": 'Cosa via aspettate da vostro padre e vostra madre come ereditá (quanti soldi)',
        "tooltip": 'Cosa vi aspettate di ereditare',
    },
    {
        "id": 37,
        "x" : 5,
        "y" : 5,
        "title": 'Cos\' é #37',
        "description": 'Che oggetto possedete di vostra nonna materna',
        "tooltip": 'Oggetto di vostra nonna',
    },
    {
        "id": 38,
        "x" : 1,
        "y" : 5,
        "title": 'Cos\' é #38',
        "description": 'Il mio piú grande sogno da piccolo, cosa volevo diventare',
        "tooltip": 'Il piú grande sogno da piccolo',
    },
    {
        "id": 39,
        "x" : 6,
        "y" : 5,
        "title": 'Cos\' é #39',
        "description": 'La vostra piú grande paura',
        "tooltip": 'La piú grande paura',
    },
    {
        "id": 40,
        "x" : 0,
        "y" : 5,
        "title": 'Cos\' é #40',
        "description": 'Avete realizzato il vostro piú grande sogno o siete falliti',
        "tooltip": 'realizzato il vostro piú grande sogno',
    },
    {
        "id": 41,
        "x" : 1,
        "y" : 6,
        "title": 'Cos\' é #41',
        "description": 'Qual\'é il piú grande sogno ora',
        "tooltip": 'Il piú grande sogno ora',
    },
    {
        "id": 42,
        "x" : 5,
        "y" : 6,
        "title": 'Cos\' é #42',
        "description": 'Cosa possedete che é come a vostra nonna materna',
        "tooltip": 'Cosa avete che assomiglia a vostra nonna materna',
    },
    {
        "id": 43,
        "x" : 6,
        "y" : 6,
        "title": 'Cos\'é #43',
        "description": 'Quando morirete? quanto a lungo é vissuta vostra nonna materna',
        "tooltip": 'Quando morirete?',
    },
    {
        "id": 44,
        "x" : 1,
        "y" : 0,
        "title": 'Chi é #44',
        "description": 'Cosa possedeva vostro nonno paterno che vostro padre voleva di piú',
        "tooltip": 'Cosa possedeva vostro nonno paterno che vostro padre voleva di piú',
    },
    {
        "id": 45,
        "x" : 0,
        "y" : 0,
        "title": 'Chi é #45',
        "description": 'Vostro nonno paterno ha mai detto a papá che lo amava',
        "tooltip": 'Vostro nonno paterno ha mai detto a papá che lo amava',
    },
    {
        "id": 46,
        "x" : 5,
        "y" : 0,
        "title": 'Chi é #46',
        "description": 'Pensate che otterrete quello che volete, materialmente? (é un atteggiamento di vostro nonno)',
        "tooltip": 'Pensate che otterrete quello che volete, materialmente?',
    },
    {
        "id": 47,
        "x" : 6,
        "y" : 0,
        "title": 'Chi é #47',
        "description": 'Cosa vedete come vostro compimento piú grande nel futuro',
        "tooltip": 'Cosa vedete come vostro compimento piú grande nel futuro',
    },
    {
        "id": 48,
        "x" : 0,
        "y" : 6,
        "title": 'Chi é #48',
        "description": 'Il piú grande compimento che costituisce voi',
        "tooltip": 'Il piú grande compimento',
    },
  ]
}

// mock part
var answer = MockUserData;


module.exports = function (){
    Block.remove();
    console.info("Removed all");

    for(index in questions.items){
        var question = questions.items[index];

        var block = new Block({
            _id: question.id,
            title: question.title,
            description: question.description,
            tooltip: question.tooltip,
            x: question.x,
            y: question.y,
            value: answer[question.id],
            enabled: true
        });
        Block.create(block);
        console.info("Create block " + block);
    }
    console.info("Generation completed");
}
